In [ ]:
import numpy as np


## Workut Rough

In [ ]:
arr=np.random.randint(1,100,10)
arr


array([91, 88, 64, 51, 38, 54, 67, 65, 99, 36])

In [ ]:
np.mean(arr)

58.3

In [ ]:
np.var(arr)

336.40999999999997

In [ ]:
arr=np.append(arr ,[1000,2000])

In [ ]:
np.mean(arr)

298.5833333333333

In [ ]:
arr

array([  37,   55,   70,   63,   30,   70,   77,   30,   81,   70, 1000,
       2000])

In [ ]:
arr= np.loadtxt('cric_data.tsv', skiprows=1,
                usecols=[1,2,3])

In [ ]:
np.shape(arr)

(225, 3)

In [ ]:
np.mean(arr[:,0])

39.87555555555556

## Problem 1,2,3

In [ ]:
sachin=arr[:,0]

In [ ]:
rahul=arr[:,1]

In [ ]:
india=arr[:,2]

In [ ]:
np.mean(sachin)

39.87555555555556

In [ ]:
def stats(cols):
  print('Mean',np.mean(cols))
  print('Median',np.median(cols))
  print('IQR',((np.percentile(cols,75))-np.percentile(cols,25)))

In [ ]:
stats(sachin)

Mean 39.87555555555556
Median 27.0
IQR 57.0


In [ ]:
stats(rahul)

Mean 32.062222222222225
Median 22.0
IQR 46.0


In [ ]:
stats(india)

Mean 220.79555555555555
Median 216.0
IQR 98.0


In [ ]:
np.histogram(sachin,bins=[0,20,40,60,80,100,120,140,160,180,200])

(array([100,  40,  24,  17,  18,  11,   7,   7,   0,   1]),
 array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200]))

In [ ]:
np.histogram(sachin,bins=10)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

In [ ]:
np.mean(sachin.reshape(9,25),axis=1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

## Problem 4,5


In [ ]:
np.mean(sachin[sachin>=100])

125.0

In [ ]:
np.mean(sachin[rahul<=10])

40.2112676056338

##Problem 6



In [ ]:
qrs=np.percentile(india,[25,50,75,100])

In [ ]:
np.mean(sachin[india<175])

19.672727272727272

In [ ]:
np.shape(qrs)

(4,)

In [ ]:
qrs=qrs.reshape(4,1)

In [ ]:
indices =india<qrs

In [ ]:
np.shape(indices)

(4, 225)

In [ ]:
sachin[indices[0,:]]

array([18., 14.,  0., 62., 46., 65.,  0., 39., 48.,  3., 11., 65., 27.,
       28.,  3.,  4., 15., 40.,  5.,  8., 89.,  0.,  0.,  1.,  0.,  0.,
       81., 13.,  2., 36., 12., 19.,  0.,  6., 35.,  0., 44.,  3., 47.,
       17., 35., 33.,  7.,  9.,  2., 11., 17.,  1., 10.,  0., 23.,  1.,
        2., 25.,  0.])

In [ ]:
for i in range(4):
  print(i,np.mean(sachin[indices[i]]))

0 19.672727272727272
1 28.18018018018018
2 31.688622754491018
3 39.799107142857146


##Problem 7


In [ ]:
most=arr[:,0:2]

In [ ]:
tru=np.argmax(most,axis=1) 


In [ ]:
np.where(tru==0,'Sachin','Rahul')

array(['Sachin', 'Rahul', 'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin',
       'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Sachin', 'Sachin'

In [ ]:
print(np.sum(tru) ,' matches rahul has scored more than Sachin') 

106  matches rahul has scored more than Sachin


##Problem 8,9

In [ ]:
s_scores=np.cumsum(sachin)

In [ ]:
np.histogram(s_scores,bins=[0,1000,2000,3000,4000,5000,6000,7000,8000,9000])

(array([29, 18, 26, 25, 26, 26, 23, 22, 30]),
 array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]))

##Sample

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a[1][2])

6


In [ ]:
a=np.arange(3)
b=a.reshape(2,2)
print(b)

ValueError: ignored

In [ ]:
a=np.arange(10)
b=np.where(a %2==1,1,a)
print(b)

[0 1 2 1 4 1 6 1 8 1]


In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a=np.array([1,2,3,4,5])
print(a[::-1])

[5 4 3 2 1]


In [ ]:
a=np.array([1,2,3,4,5])
a[0]=0.9
print(a[0],a.dtype)

0 int64


In [ ]:
a=np.array([1.0,2.2,3.5])
a=a/0.0
print(a[0])

inf


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [ ]:
a=np.array([3,6,9,12,15])
b=np.array([2,4,6,8,12])
c=np.where(a==b)
print(c)

(array([], dtype=int64),)


In [ ]:
a=a=np.array([1,2,3,4,5])
print(a[2:None])

[3 4 5]
